title: Lek Peng # your name (or website title) here
logo: "/images/profile-picture.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistician and Aspiring Software Engineer <br><br> Through a self-initiated web-scraping project to improve operational
  efficiency, I discovered my love for software engineering. Seeing how peopleâ€™s lives can be transformed through technology
  brought me great joy, and I strive to keep learning and growing to continue making a positive impact.  <br><br> <a
  href="https://www.linkedin.com/in/lek-peng/">View My LinkedIn Profile</a>  <br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
